// PDF Export utility for Study Plan
// Note: For production, install jsPDF: npm install jspdf

export const exportStudyPlanToPDF = (studyPlan, studentData, riskAnalysis) => {
  // Create a formatted text version for download
  let content = `
AI STUDY COACH - PERSONALIZED STUDY PLAN
========================================

Generated: ${new Date().toLocaleDateString()}
Risk Level: ${riskAnalysis?.risk_level || 'N/A'}
Confidence: ${riskAnalysis?.confidence || 'N/A'}%

LEARNING DIAGNOSIS
==================

Strengths:
${studyPlan.diagnosis.strengths.map((s, i) => `${i + 1}. ${s}`).join('\n')}

Areas for Improvement:
${studyPlan.diagnosis.weaknesses.map((w, i) => `${i + 1}. ${w}`).join('\n')}

Risk Factors:
${studyPlan.diagnosis.riskFactors.map((r, i) => `${i + 1}. ${r}`).join('\n')}

STUDY PLAN OVERVIEW
===================
${studyPlan.studyPlan.overview}

WEEKLY BREAKDOWN
================
${studyPlan.studyPlan.weeks.map((week) => `
Week ${week.week}: ${week.focus}
${'='.repeat(50)}

Goals:
${week.goals.map((g, i) => `  ${i + 1}. ${g}`).join('\n')}

Activities:
${week.activities.map((a, i) => `  ${i + 1}. ${a}`).join('\n')}
`).join('\n')}

MILESTONES
==========
${studyPlan.milestones.map((m) => `
Week ${m.week}: ${m.milestone}
Target: ${m.target}
`).join('\n')}

RECOMMENDED RESOURCES
=====================
${studyPlan.resources.map((r, i) => `
${i + 1}. ${r.title} (${r.type})
   ${r.description}
   URL: ${r.url}
`).join('\n')}

STUDY RECOMMENDATIONS
=====================
${studyPlan.recommendations.map((r, i) => `${i + 1}. ${r}`).join('\n')}

---
Generated by AI Study Coach
© 2024 All Rights Reserved
`;

  // Create blob and download
  const blob = new Blob([content], { type: 'text/plain' });
  const url = window.URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `study-plan-${new Date().toISOString().split('T')[0]}.txt`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  window.URL.revokeObjectURL(url);
};

// For future implementation with jsPDF
export const exportStudyPlanToPDFAdvanced = (studyPlan, studentData, riskAnalysis) => {
  // This would use jsPDF library for better formatting
  // Install: npm install jspdf
  // import jsPDF from 'jspdf';
  
  console.log('Advanced PDF export - Install jsPDF for full functionality');
  // Fallback to text export
  exportStudyPlanToPDF(studyPlan, studentData, riskAnalysis);
};
